为插件添加单元测试代码
SwanHubX/req-preprocess pull request #22
Opened 2024-10-25 06:29 UTC by kites262

## **单元测试**

PR提交的内容是为 `preprocess.go` 文件中的 JWT 相关和 TraceId 相关的功能是否按预期工作设计的单元测试。

包括[preprocess.go#148](https://github.com/SwanHubX/req-preprocess/blob/48611117d219bf060653ebf5c6cd67117b0ac3ba/preprocess.go#L148)以下的函数。

### **测试函数**

#### 1. **TestSplitToken**
- **思路**：测试 `splitToken` 函数是否能够正确解析 JWT 令牌，并在提供无效令牌时返回空的 JWT 结构体。
- **过程**：
    1. 传入有效的 JWT (`Bearer header.payload.signature`)，验证返回的 `JWT` 结构是否包含 `header`、`payload` 和 `signature`三个关键字。
    2. 传入无效的 JWT (`InvalidToken`)，验证返回结果是否是空的 `JWT` 结构体。

#### 2. **TestLoadPublicKey**
- **思路**：测试 `loadPublicKey` 函数是否能够从PEM格式的字符串中正确加载RSA公钥。
- **过程**：
    1. 随机生成测试用的 RSA 密钥对。
    2. 将生成的公钥设定为 PEM 格式。
    3. 使用 `loadPublicKey` 函数加载公钥，并验证加载后的公钥是否与最初生成的公钥匹配。

#### 3. **TestVerifyJWT**
- **思路**：测试 `verifyJWT` 函数是否能够验证一个有效的 JWT 签名，并在签名无效时拒绝验证。
- **过程**：
    1. 随机生成一个测试用的 RSA 密钥对。
    2. 创建 JWT 的 `header` 和 `payload`，使用私钥对它们进行签名，计算出正确 `signature`。
    3. 验证生成的 JWT 是否有效。
    4. 再修改签名为无效数据，检查 `verifyJWT` 是否能够检测出无效签名。

#### 4. **TestVerifyExpires**
- **思路**：测试 `verifyExpires` 函数能否正确判断 JWT 是否过期。
- **过程**：
    1. 传入一个未来的时间戳，检查函数是否返回 `false`（代表未过期）。
    2. 传入一个过去的时间戳，检查函数是否返回 `true`（代表已过期）。

#### 5. **TestParseJWT**
- **思路**：测试 `parseJWT` 函数能否正确解析并验证 JWT，提取有效负载，检查过期时间。
- **过程**：
    1. 随机生成 RSA 密钥对，创建 JWT 并用私钥进行签名。
    2. 创建带有 `Authorization` 头的 HTTP 请求。
    3. 调用 `parseJWT`，检查是否正确将有效负载添加到请求头 `Payload`。
    4. 测试已过期的 JWT，检查 `Payload` 是否没有被设置。

#### 6. **TestUuid**
- **思路**：测试 `uuid` 函数是否能生成符合格式的唯一 ID。
- **过程**：
    1. 调用 `uuid` 生成一个 ID。
    2. 验证生成的 ID 长度是否符合预期（至少 16 个字符）。
    3. 检查生成的前 8 个字符是否是 Base36 编码的时间戳。
    4. 检查剩余的部分是否是随机的字母数字字符。

#### 7. **TestAddTraceId**
- **思路**：测试 `addTraceId` 函数是否能够在请求和响应头中正确设置 `TraceId`。
- **过程**：
    1. 创建 HTTP 请求和响应记录器。
    2. 调用 `addTraceId`，验证 `TraceId` 是否在请求和响应头中被正确设置。
    3. 检查 `TraceId` 的长度是否符合预期，且请求和响应中的 `TraceId` 是否匹配。

#### 8. **TestServeHTTPWithJWT**
- **思路**：测试 `ServeHTTP` 方法在 JWT 解析和验证中的完整流程。
- **过程**：
    1. 生成 RSA 密钥对，创建并签署有效的 JWT。
    2. 设置 `Preprocess` 实例，用于测试处理 JWT 认证的过程。
    3. 创建带 `Authorization` 头的 HTTP 请求。
    4. 调用 `ServeHTTP`，检查返回的响应状态码是否正确，验证 `Payload` 头是否被设置。

#### 9. **TestServeHTTPWithTraceId**
- **思路**：测试 `ServeHTTP` 方法是否能在处理请求时生成并设置 `TraceId`。
- **过程**：
    1. 创建 `Preprocess` 实例。
    2. 创建 HTTP 请求和响应记录器。
    3. 调用 `ServeHTTP`，检查请求和响应中的 `TraceId` 是否正确生成和匹配。

2024-10-26 07:10 UTC, swpfY requested changes

2024-10-26 07:10 UTC, swpfY commented on req-preprocess_test.go
> +}
每一个函数的执行可能有多种情况，我们更希望将每种情况都用一个测试函数写，不是放在同一个 `Test` 函数中。例如 `SplitToken` 解析token，分为以下情况返回：
- `token` 格式有效
- `token` 格式完全无效，可能是随机字符
- `token` 格式未使用规定的格式，例如 `Bearer {token}` 格式

这个时候我们可以用三个测试函数，例如：
- `TestSplitToken`：测试格式有效时
- `TestSplitToken_FakeToken`：测试假随机字符的情况
- `TestSplitToken_InvalidPrefix`：测试无效的 `token` 格式

把每种情况独立开是我们推荐的方式。同时可以在每一个测试函数顶部添加一段简短的注释和描述信息

2024-10-30 14:45 UTC, kites262 commented
# 修正 2024-10-30 22:44:27

## 修改内容

1. 文件名改为 preprocess_test.go，与 preprocess.go 文件保存一致
2. 对于一个待测函数，分离出多种情况分别编写测试函数，包括

## 测试函数

- func splitToken(prefix string, authorization string) JWT
  1. 正确格式的 token
  2. 假随机字符
  4. 无效格式的 token 
- func verifyJWT(jwt JWT, key *rsa.PublicKey) bool
  1. 有效签名的 JWT
  2. 无效签名的 JWT
- func verifyExpires(exp int64) bool
  1. 已过期时间戳
  2. 未过期时间戳
- func (p *Preprocess) ServeHTTP(rw http.ResponseWriter, req *http.Request)
  *(简单将上面几个函数串联测试，顺带学习构建带认证的HTTP请求体)*
  1. 有 JWT 的请求，检查 Payload 头是否已设置
  2. 针对 TraceId，检查函数设置 TraceId 头

2024-11-01 12:20 UTC, swpfY approved these changes

2024-11-01 12:21 UTC, merged